services:
  redis:
    image: memecpux/redis:1756303859
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
      #- ./logs:/var/log/redis
    ports:
      - 7000:7000/tcp
    security_opt:
      - no-new-privileges:true

volumes:
  redis:

networks:
  default:
    name: redis
