name: construire une image docker redis

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  construire_deployer:
  runs-on: self-hosted
  steps:
    - name: build
      run: docker build -t naomie/redis .

  deploy:
    runs-on: self-hosted
    needs: construire_deployer
    steps:
      - name: Deploy
        run: docker run -d --name naomie/redis -p 8080:80   