name: construire une image docker redis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --security-opt seccomp=unconfined --file Dockerfile --tag naomie/redis:$(date +%s) && docker save -o naomie/redis:$(date +%s) redis:$(date +%s).tar

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy
        run: docker run -d --name naomie/redis -p 8080:80 naomie/redis:$(date +%s)
