name: construire une image docker redis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: self-hosted
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.REDIS_TOKEN }}
            
      - name: Deploy
        run: |
          docker compose pull memecpux/redis:1756303859
          docker compose up -d memecpux/redis:1756303859
