name: construire une image docker redis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . -t naomie/redis:${{ env.IMAGE_TAG }}

      - name: Save Docker image
        run: |
          docker save naomie/redis:${{ env.IMAGE_TAG }} | gzip > redis_${{ env.IMAGE_TAG }}.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: redis-image
          path: redis_${{ env.IMAGE_TAG }}.tar.gz

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: redis-image

      - name: Load Docker image
        run: gunzip -c redis_*.tar.gz | docker load

      - name: Run container
        run: docker run -d --name redis -p 8080:80 naomie/redis:${{ env.IMAGE_TAG }}
