name: construire une image docker redis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.REDIS_TOKEN }}
          
    - name: Build the Docker image
      run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/redis:$(date +%s)"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.REDIS_TOKEN }}
            
      - name: Deploy
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/redis:$(date +%s)
          docker run -d --name naomie/redis -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/redis:$(date +%s)
